services:
  - type: web
    name: mathrix-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://mathrix-backend.onrender.com
      - key: REACT_APP_ENABLE_ANALYTICS
        value: false
      - key: REACT_APP_ENABLE_DEBUG
        value: false
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - tailwind.config.js
        - postcss.config.js
